name: C++ CI

on:
  pull_request

jobs:
  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Set execute permissions for check-lines.sh
        run: chmod +x ci-scripts/check-lines.sh

      - name: Check line breaks
        run: |
          pushd $GITHUB_WORKSPACE
          ci-scripts/check-lines.sh
          popd

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '17'
          check-path: 'src tests'
          exclude-regex: '.*itti_structs.*'

  test:
    needs: formatting-check
    name: Tests in ${{ matrix.build_type }} with ${{ matrix.compiler }}

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, SanitizedDebug]
        compiler: [ gcc-13, clang-17 ]

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Vcpkg
        uses: microsoft/setup-vcpkg@v1
        with:
          vcpkg-root: '/home/vcpkg'

      - name: Install GCC 13
        if: matrix.compiler == 'gcc-13'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

      - name: Install Clang 17
        if: matrix.compiler == 'clang-17'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-17
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=/home/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build project
        run: cmake --build build --target tests -- -j 4

      - name: Run tests
        run: |
          if [[ ${{ matrix.build_type }} == "SanitizedDebug" ]]; then
            ASAN_OPTIONS=alloc_dealloc_mismatch=0 ./build/tests
          else
            ./build/tests
          fi
